version: 2.1

commands:
  verify-install-container:
    steps:
      - run: /opt/solarwinds/uamsclient/sbin/uamsclient version
  verify-install-vm:
    steps:
      - run: ps -aux | grep "uamsclient start" | grep -v grep
  verify-uninstall:
    steps:
      - run: if [ -d "/opt/solarwinds/uamsclient" ]; then exit 1; fi
  install-saltstack-script-vm:
    steps:
      - run: |
          curl -o bootstrap-salt.sh -L https://github.com/saltstack/salt-bootstrap/releases/latest/download/bootstrap-salt.sh
          chmod +x bootstrap-salt.sh
          sudo ./bootstrap-salt.sh -M -X
  install-saltstack-fedora:
    steps:
      - run: |
          curl -fsSL https://github.com/saltstack/salt-install-guide/releases/latest/download/salt.repo | sudo tee /etc/yum.repos.d/salt.repo
          yum clean expire-cache
          yum install salt-minion -y
  prepare-saltstack:
    steps:
      - run: |
          sudo mkdir -p /srv/salt/uamsclient && sudo cp -r ./uamsclient/* /srv/salt/uamsclient/
          sudo mkdir -p /srv/pillar && sudo cp -r ./test/pillar/* /srv/pillar/
  prepare-saltstack-container:
    steps:
      - run: |
          mkdir -p /srv/salt/uamsclient && cp -r ./uamsclient/* /srv/salt/uamsclient/
          mkdir -p /srv/pillar && cp -r ./test/pillar/* /srv/pillar/

  test-saltstack:
    steps:
      - run: |
          sudo salt-call --local test.ping
  test-saltstack-container:
    steps:
      - run: |
          salt-call --local test.ping

  install-client:
    steps:
      - run: |
          sudo salt-call --local state.apply uamsclient.install -l debug

  uninstall-client:
    steps:
      - run: |
          sudo salt-call --local state.apply uamsclient.clean -l debug

  install-client-container:
    steps:
      - run: |
          salt-call --local state.apply uamsclient.install pillar='{"is_container": "true"}' -l debug || true

jobs:
  run-ubuntu-vm:
    description: Install VM
    machine:
      image: ubuntu-2004:current
    resource_class: small
    steps:
      - checkout
      - prepare-saltstack
      - install-saltstack-script-vm
      - test-saltstack
      - install-client
      - verify-install-vm
      - uninstall-client
      - verify-uninstall

  saltstack-linter:
    docker:
      - image: cimg/python:3.12.4
    steps:
      - checkout
      - run:
          name: Python version
          command: python --version
      - run:
          name: Install salt-lint
          command: pip install salt-lint
      - run:
          name: Run salt-lint
          command: find . -type f -name "*.sls" | xargs salt-lint

  run-fedora-32:
    docker:
      - image: fedora:32
    steps:
      - checkout
      - install-saltstack-fedora
      - prepare-saltstack-container
      - test-saltstack-container
      - install-client-container
      - verify-install-container
      - uninstall-client
      - verify-uninstall

  run-fedora-36:
    docker:
      - image: fedora:36
    steps:
      - checkout
      - install-saltstack-fedora
      - prepare-saltstack-container
      - test-saltstack-container
      - install-client-container
      - verify-install-container
      - uninstall-client
      - verify-uninstall

  run-fedora-38:
    docker:
      - image: fedora:38
    steps:
      - checkout
      - prepare-saltstack-container
      - install-saltstack-fedora
      - test-saltstack-container
      - install-client-container
      - verify-install-container
      - uninstall-client
      - verify-uninstall

workflows:
  test-and-uamsclient-formula: 
    jobs:
      - saltstack-linter
      - run-ubuntu-vm
      - run-fedora-32
      - run-fedora-36
      - run-fedora-38